//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationTracking
    {
        public string MessageId { get; set; }
        public string UserId { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public string MessageTyppe { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string RelatedMsgId { get; set; }
        public System.DateTime SentDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual CommunicationInfo CommunicationInfo { get; set; }
    }
}
