//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationInfo
    {
        public CommunicationInfo()
        {
            this.CommunicationTrackings = new HashSet<CommunicationTracking>();
        }
    
        public string MessageId { get; set; }
        public string ToList { get; set; }
        public string CCList { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public string MessageTyppe { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual ICollection<CommunicationTracking> CommunicationTrackings { get; set; }
    }
}
