//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Id { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> HolidayDate { get; set; }
        [Display(Name = "Day")]
        public string HolidayDay { get; set; }
    }
}
