//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public byte Id { get; set; }
        [Display(Name = "Message")]
        public string Message1 { get; set; }
        [Display(Name = "Message Code")]
        public string MessageCode { get; set; }
    }
}
