//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentTrackingEntities : DbContext
    {
        public StudentTrackingEntities()
            : base("name=StudentTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PrimaryTag> PrimaryTags { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolBranch> SchoolBranches { get; set; }
        public virtual DbSet<SecondaryTag> SecondaryTags { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<StaffDetail> StaffDetails { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
    }
}
