//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolBranch
    {
        public SchoolBranch()
        {
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        [Display(Name = "School Id")]
        public Nullable<int> SchoolId { get; set; }
        [Display(Name = "Contact Detail")]
        public string Contact_Detail { get; set; }
        [Display(Name = "Branch Code")]
        public string Branch_Code { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
    }
}
