//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.StaffDetails = new HashSet<StaffDetail>();
            this.StudentDetails = new HashSet<StudentDetail>();
            this.Users = new HashSet<User>();
            this.SyllabusDetails = new HashSet<SyllabusDetail>();
            this.TimeTables = new HashSet<TimeTable>();
            this.SemesterDetails = new HashSet<SemesterDetail>();
            this.StudentResults = new HashSet<StudentResult1>();
        }
    
        public string Name { get; set; }
        public string BranchName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ContactPerson { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string EmailId { get; set; }
        public string Description { get; set; }
        public string FaceBookUrl { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public int OrganizationId { get; set; }
        public int ThemeId { get; set; }
        public string IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ID { get; set; }
        public string AppId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual ICollection<StaffDetail> StaffDetails { get; set; }
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<SyllabusDetail> SyllabusDetails { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
        public virtual ICollection<SemesterDetail> SemesterDetails { get; set; }
        public virtual ICollection<StudentResult1> StudentResults { get; set; }
    }
}
