//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondaryTag
    {
        public SecondaryTag()
        {
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public long Id { get; set; }
        public string TagId { get; set; }
        public string IP_Address { get; set; }
        public string TagInformation1 { get; set; }
        public string TagInformation2 { get; set; }
    
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
    }
}
