//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterDetail
    {
        public SemesterDetail()
        {
            this.StudentResults = new HashSet<StudentResult1>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalMarks { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<StudentResult1> StudentResults { get; set; }
    }
}
