//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        public string StaffId { get; set; }
        public string StaffName { get; set; }
        public Nullable<byte> Department { get; set; }
        public Nullable<long> PrimaryTagId { get; set; }
        public string ReportingEmailId { get; set; }
        public string StaffMobileNo { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public int ID { get; set; }
    }
}
