//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int ID { get; set; }
        public int SyllabusDetails { get; set; }
        public int StudentId { get; set; }
        public decimal MarksObtained { get; set; }
        public string GradeObtained { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual SyllabusDetail SyllabusDetail { get; set; }
    }
}
