//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Id { get; set; }
        [Display(Name = "Student Id")]
        public string StudentId { get; set; }
        [Display(Name = "Parent Mobile No")]
        public string ParentMobileNo { get; set; }
        [Display(Name = "Primary Tag Id")]
        public Nullable<long> PrimaryTagId { get; set; }
        [Display(Name = "Secondary Tag Id")]
        public Nullable<long> SecondaryTagId { get; set; }
        [Display(Name = "Email Id")]
        public string EmailId { get; set; }
        [Display(Name = "Student Name")]
        public string StudentName { get; set; }
        [Display(Name = "School Branch")]
        public Nullable<int> SchoolBranchId { get; set; }
        
        public Nullable<int> ClassId { get; set; }
       
        public Nullable<int> SectionId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual PrimaryTag PrimaryTag { get; set; }
        public virtual SchoolBranch SchoolBranch { get; set; }
        public virtual SecondaryTag SecondaryTag { get; set; }
        public virtual Section Section { get; set; }
    }
}
