//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public long Id { get; set; }
        public Nullable<long> PrimaryTagId { get; set; }
        public Nullable<long> SecondaryTagId { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<bool> IntimeMessageSendStatus { get; set; }
        public Nullable<bool> OutTimeMessageSentStatus { get; set; }
        public Nullable<System.DateTime> NextRuntime { get; set; }
        public Nullable<System.DateTime> LastRuntime { get; set; }
        public Nullable<System.DateTime> LockAcquired { get; set; }
        public Nullable<System.DateTime> LockExpire { get; set; }
        public Nullable<System.Guid> LockUid { get; set; }
        public Nullable<int> LockProcessId { get; set; }
        public Nullable<int> ProcessRetryCount { get; set; }
        public Nullable<int> LockRetryCount { get; set; }
        public Nullable<System.DateTime> TagReadingTime { get; set; }
        public Nullable<short> NoOftimeTimeTagRead { get; set; }
    
        public virtual PrimaryTag PrimaryTag { get; set; }
        public virtual SecondaryTag SecondaryTag { get; set; }
    }
}
