//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string ParentMobileNo { get; set; }
        public int PrimaryTagId { get; set; }
        public int SecondaryTagId { get; set; }
        public string EmailId { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> SchoolBranchId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirthh { get; set; }
        public string ParentName { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual School School { get; set; }
        public virtual Section Section { get; set; }
        public virtual TagDetail TagDetail { get; set; }
    }
}
