//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyllabusTracking
    {
        public int ID { get; set; }
        public int SyllabusID { get; set; }
        public int SectionId { get; set; }
        public Nullable<decimal> PerCompleted { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual SyllabusDetail SyllabusDetail { get; set; }
    }
}
