//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagDetail
    {
        public TagDetail()
        {
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public int ID { get; set; }
        public string TagId { get; set; }
        public string IsActive { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
    }
}
