//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ID { get; set; }
        public int ClassId { get; set; }
        public int SectionId { get; set; }
        public int LectureId { get; set; }
        public string Days { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual LectureDuration LectureDuration { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
